[window]
decorations = "buttonless" # buttonless / none / full
dynamic_padding = true
opacity = 0.9

[window.position]
x = 2561
y = 0

[window.padding]
x = 2
y = 2

[font]
size = 12.5
normal = { family = "0xProtoNerdFont", style = "Regular" }
# Ligne optionnelle pour activer ou désactiver le "bold"
bold = { family = "0xProtoNerdFont", style = "Bold" }

[general]
live_config_reload = true
